-- Countries Master Data
-- Run this script to populate the countries table

-- Create table if not exists
CREATE TABLE IF NOT EXISTS countries (
  id SERIAL PRIMARY KEY,
  code VARCHAR(10) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Insert or update countries
INSERT INTO countries (code, name, is_active) VALUES
('AD', 'Andorra', true),
('AE', 'United Arab Emirates', true),
('AL', 'Albania', true),
('AM', 'Armenia', true),
('AO', 'Angola', true),
('AR', 'Argentina', true),
('AT', 'Austria', true),
('AU', 'Australia', true),
('AZ', 'Azerbaijan', true),
('BA', 'Bosnia and Herzegovina', true),
('BD', 'Bangladesh', true),
('BE', 'Belgium', true),
('BG', 'Bulgaria', true),
('BH', 'Bahrain', true),
('BM', 'Bermuda', true),
('BN', 'Brunei Darussalam', true),
('BO', 'Bolivia', true),
('BR', 'Brazil', true),
('BS', 'Bahamas', true),
('BW', 'Botswana', true),
('CA', 'Canada', true),
('CH', 'Switzerland', true),
('CL', 'Chile', true),
('CM', 'Cameroon', true),
('CN', 'China', true),
('CO', 'Colombia', true),
('CR', 'Costa Rica', true),
('CY', 'Cyprus', true),
('CZ', 'Czechia', true),
('DE', 'Germany', true),
('DK', 'Denmark', true),
('DO', 'Dominican Republic', true),
('DZ', 'Algeria', true),
('EC', 'Ecuador', true),
('EE', 'Estonia', true),
('EG', 'Egypt', true),
('EL', 'Greece', true),
('ES', 'Spain', true),
('ET', 'Ethiopia', true),
('FI', 'Finland', true),
('FJ', 'Fiji Islands', true),
('FO', 'Faroe Islands', true),
('FR', 'France', true),
('GB', 'Great Britain', true),
('GE', 'Georgia', true),
('GG', 'Guernsey', true),
('GH', 'Ghana', true),
('GL', 'Greenland', true),
('GT', 'Guatemala', true),
('HK', 'Hong Kong', true),
('HN', 'Honduras', true),
('HR', 'Croatia', true),
('HU', 'Hungary', true),
('ID', 'Indonesia', true),
('IE', 'Ireland', true),
('IL', 'Israel', true),
('IM', 'Isle of Man', true),
('IN', 'India', true),
('IS', 'Iceland', true),
('IT', 'Italy', true),
('JE', 'Jersey', true),
('JM', 'Jamaica', true),
('JO', 'Jordan', true),
('JP', 'Japan', true),
('KE', 'Kenya', true),
('KH', 'Cambodia', true),
('KR', 'South Korea', true),
('KW', 'Kuwait', true),
('KY', 'Cayman Islands', true),
('KZ', 'Kazakhstan', true),
('LB', 'Lebanon', true),
('LI', 'Liechtenstein', true),
('LK', 'Sri Lanka', true),
('LT', 'Lithuania', true),
('LU', 'Luxembourg', true),
('LV', 'Latvia', true),
('MA', 'Morocco', true),
('MC', 'Monaco', true),
('ME', 'Montenegro', true),
('MG', 'Madagascar', true),
('MK', 'North Macedonia', true),
('MN', 'Mongolia', true),
('MO', 'Macao', true),
('MT', 'Malta', true),
('MU', 'Mauritius', true),
('MV', 'Maldives', true),
('MW', 'Malawi', true),
('MX', 'Mexico', true),
('MY', 'Malaysia', true),
('MZ', 'Mozambique', true),
('NA', 'Namibia', true),
('NG', 'Nigeria', true),
('NI', 'Northern Ireland', true),
('NL', 'Netherlands', true),
('NO', 'Norway', true),
('NP', 'Nepal', true),
('NZ', 'New Zealand', true),
('OM', 'Oman', true),
('PA', 'Panama', true),
('PE', 'Peru', true),
('PH', 'Philippines', true),
('PK', 'Pakistan', true),
('PL', 'Poland', true),
('PR', 'Puerto Rico', true),
('PT', 'Portugal', true),
('PY', 'Paraguay', true),
('QA', 'Qatar', true),
('RO', 'Romania', true),
('RS', 'Serbia', true),
('RU', 'Russia', true),
('SA', 'Saudi Arabia', true),
('SB', 'Solomon Islands', true),
('SE', 'Sweden', true),
('SG', 'Singapore', true),
('SI', 'Slovenia', true),
('SK', 'Slovakia', true),
('SM', 'San Marino', true),
('SN', 'Senegal', true),
('ST', 'São Tomé and Príncipe', true),
('SV', 'El Salvador', true),
('SZ', 'Swaziland', true),
('TH', 'Thailand', true),
('TN', 'Tunisia', true),
('TR', 'Türkiye', true),
('TT', 'Trinidad and Tobago', true),
('TW', 'Taiwan', true),
('TZ', 'Tanzania', true),
('UA', 'Ukraine', true),
('UG', 'Uganda', true),
('US', 'USA', true),
('UY', 'Uruguay', true),
('VG', 'British Virgin Islands', true),
('VN', 'Vietnam', true),
('VU', 'Vanuatu', true),
('WS', 'Samoa', true),
('XK', 'Kosovo', true),
('ZA', 'South Africa', true),
('ZM', 'Zambia', true),
('ZW', 'Zimbabwe', true)
ON CONFLICT (code) 
DO UPDATE SET 
  name = EXCLUDED.name,
  updated_at = NOW();

-- Verify the data
SELECT COUNT(*) as total_countries FROM countries;
SELECT * FROM countries ORDER BY name LIMIT 10;
