-- Countries Master Data
-- Run this script to populate the countries table

-- Create table if not exists
CREATE TABLE IF NOT EXISTS countries (
  id SERIAL PRIMARY KEY,
  code VARCHAR(10) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  currency_code VARCHAR(10),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Add currency_code column if missing (safe for existing tables)
ALTER TABLE countries ADD COLUMN IF NOT EXISTS currency_code VARCHAR(10);

-- Insert or update countries
INSERT INTO countries (code, name, currency_code, is_active) VALUES
('AD', 'Andorra', 'EUR', true),
('AE', 'United Arab Emirates', 'AED', true),
('AL', 'Albania', 'ALL', true),
('AM', 'Armenia', 'AMD', true),
('AO', 'Angola', 'AOA', true),
('AR', 'Argentina', 'ARS', true),
('AT', 'Austria', 'EUR', true),
('AU', 'Australia', 'AUD', true),
('AZ', 'Azerbaijan', 'AZN', true),
('BA', 'Bosnia and Herzegovina', 'BAM', true),
('BD', 'Bangladesh', 'BDT', true),
('BE', 'Belgium', 'EUR', true),
('BG', 'Bulgaria', 'BGN', true),
('BH', 'Bahrain', 'BHD', true),
('BM', 'Bermuda', 'BMD', true),
('BN', 'Brunei Darussalam', 'BND', true),
('BO', 'Bolivia', 'BOB', true),
('BR', 'Brazil', 'BRL', true),
('BS', 'Bahamas', 'BSD', true),
('BW', 'Botswana', 'BWP', true),
('CA', 'Canada', 'CAD', true),
('CH', 'Switzerland', 'CHF', true),
('CL', 'Chile', 'CLP', true),
('CM', 'Cameroon', 'XAF', true),
('CN', 'China', 'CNY', true),
('CO', 'Colombia', 'COP', true),
('CR', 'Costa Rica', 'CRC', true),
('CY', 'Cyprus', 'EUR', true),
('CZ', 'Czechia', 'CZK', true),
('DE', 'Germany', 'EUR', true),
('DK', 'Denmark', 'DKK', true),
('DO', 'Dominican Republic', 'DOP', true),
('DZ', 'Algeria', 'DZD', true),
('EC', 'Ecuador', 'USD', true),
('EE', 'Estonia', 'EUR', true),
('EG', 'Egypt', 'EGP', true),
('EL', 'Greece', 'EUR', true),
('ES', 'Spain', 'EUR', true),
('ET', 'Ethiopia', 'ETB', true),
('FI', 'Finland', 'EUR', true),
('FJ', 'Fiji Islands', 'FJD', true),
('FO', 'Faroe Islands', 'DKK', true),
('FR', 'France', 'EUR', true),
('GB', 'Great Britain', 'GBP', true),
('GE', 'Georgia', 'GEL', true),
('GG', 'Guernsey', 'GBP', true),
('GH', 'Ghana', 'GHS', true),
('GL', 'Greenland', 'DKK', true),
('GT', 'Guatemala', 'GTQ', true),
('HK', 'Hong Kong', 'HKD', true),
('HN', 'Honduras', 'HNL', true),
('HR', 'Croatia', 'EUR', true),
('HU', 'Hungary', 'HUF', true),
('ID', 'Indonesia', 'IDR', true),
('IE', 'Ireland', 'EUR', true),
('IL', 'Israel', 'ILS', true),
('IM', 'Isle of Man', 'GBP', true),
('IN', 'India', 'INR', true),
('IS', 'Iceland', 'ISK', true),
('IT', 'Italy', 'EUR', true),
('JE', 'Jersey', 'GBP', true),
('JM', 'Jamaica', 'JMD', true),
('JO', 'Jordan', 'JOD', true),
('JP', 'Japan', 'JPY', true),
('KE', 'Kenya', 'KES', true),
('KH', 'Cambodia', 'KHR', true),
('KR', 'South Korea', 'KRW', true),
('KW', 'Kuwait', 'KWD', true),
('KY', 'Cayman Islands', 'KYD', true),
('KZ', 'Kazakhstan', 'KZT', true),
('LB', 'Lebanon', 'LBP', true),
('LI', 'Liechtenstein', 'CHF', true),
('LK', 'Sri Lanka', 'LKR', true),
('LT', 'Lithuania', 'EUR', true),
('LU', 'Luxembourg', 'EUR', true),
('LV', 'Latvia', 'EUR', true),
('MA', 'Morocco', 'MAD', true),
('MC', 'Monaco', 'EUR', true),
('ME', 'Montenegro', 'EUR', true),
('MG', 'Madagascar', 'MGA', true),
('MK', 'North Macedonia', 'MKD', true),
('MN', 'Mongolia', 'MNT', true),
('MO', 'Macao', 'MOP', true),
('MT', 'Malta', 'EUR', true),
('MU', 'Mauritius', 'MUR', true),
('MV', 'Maldives', 'MVR', true),
('MW', 'Malawi', 'MWK', true),
('MX', 'Mexico', 'MXN', true),
('MY', 'Malaysia', 'MYR', true),
('MZ', 'Mozambique', 'MZN', true),
('NA', 'Namibia', 'NAD', true),
('NG', 'Nigeria', 'NGN', true),
('NI', 'Nothern Ireland', 'GBP', true),
('NL', 'Netherlands', 'EUR', true),
('NO', 'Norway', 'NOK', true),
('NP', 'Nepal', 'NPR', true),
('NZ', 'New Zealand', 'NZD', true),
('OM', 'Oman', 'OMR', true),
('PA', 'Panama', 'PAB', true),
('PE', 'Peru', 'PEN', true),
('PH', 'Philippines', 'PHP', true),
('PK', 'Pakistan', 'PKR', true),
('PL', 'Poland', 'PLN', true),
('PR', 'Puerto Rico', 'USD', true),
('PT', 'Portugal', 'EUR', true),
('PY', 'Paraguay', 'PYG', true),
('QA', 'Qatar', 'QAR', true),
('RO', 'Romania', 'RON', true),
('RS', 'Serbia', 'RSD', true),
('RU', 'Russia', 'RUB', true),
('SA', 'Saudi Arabia', 'SAR', true),
('SB', 'Solomon Islands', 'SBD', true),
('SE', 'Sweden', 'SEK', true),
('SG', 'Singapore', 'SGD', true),
('SI', 'Slovenia', 'EUR', true),
('SK', 'Slovakia', 'EUR', true),
('SM', 'San Marino', 'EUR', true),
('SN', 'Senegal', 'XOF', true),
('ST', 'São Tomé and Príncipe', 'STN', true),
('SV', 'El Salvador', 'USD', true),
('SZ', 'Swaziland', 'SZL', true),
('TH', 'Thailand', 'THB', true),
('TN', 'Tunisia', 'TND', true),
('TR', 'Türkiye', 'TRY', true),
('TT', 'Trinidad and Tobago', 'TTD', true),
('TW', 'Taiwan', 'TWD', true),
('TZ', 'Tanzania', 'TZS', true),
('UA', 'Ukraine', 'UAH', true),
('UG', 'Uganda', 'UGX', true),
('US', 'USA', 'USD', true),
('UY', 'Uruguay', 'UYU', true),
('VG', 'British Virgin Islands', 'USD', true),
('VN', 'Vietnam', 'VND', true),
('VU', 'Vanuatu', 'VUV', true),
('WS', 'Samoa', 'WST', true),
('XK', 'Kosovo', 'EUR', true),
('ZA', 'South Africa', 'ZAR', true),
('ZM', 'Zambia', 'ZMW', true),
('ZW', 'Zimbabwe', 'ZWL', true)
ON CONFLICT (code)
DO UPDATE SET
  name = EXCLUDED.name,
  currency_code = EXCLUDED.currency_code,
  updated_at = NOW();

-- Verify the data
SELECT COUNT(*) as total_countries FROM countries;
SELECT code, name, currency_code FROM countries ORDER BY code LIMIT 10;
